services:
  notifier:
    container_name: notifier
    build:
      context: .
    depends_on:
      - cloudsql-proxy
    networks:
      - notifier
    restart: unless-stopped

  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    command: buildcore-prod:us-central1:buildcore --credentials-file=/secrets/cloudsql/credentials.json --address 0.0.0.0 --port 5432
    networks:
      - notifier
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    restart: unless-stopped

networks:
  notifier:
    name: notifier
    driver: bridge
