name: Firebase Functions - DEPLOY Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name:  Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions,firestore:indexes -P soonaverse -f
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
