export enum TangleRequestType {
  ADDRESS_VALIDATION = 'ADDRESS_VALIDATION',
  SELL_TOKEN = 'SELL_TOKEN',
  BUY_TOKEN = 'BUY_TOKEN',
  STAKE = 'STAKE',
  NFT_PURCHASE = 'NFT_PURCHASE',
  CLAIM_MINTED_AIRDROPS = 'CLAIM_MINTED_AIRDROPS',

  AWARD_CREATE = 'AWARD_CREATE',
  AWARD_FUND = 'AWARD_FUND',
}
