export enum TangleRequestType {
  ADDRESS_VALIDATION = 'ADDRESS_VALIDATION',
  SELL_TOKEN = 'SELL_TOKEN',
  BUY_TOKEN = 'BUY_TOKEN',
  STAKE = 'STAKE',
  NFT_PURCHASE = 'NFT_PURCHASE',
  CLAIM_MINTED_AIRDROPS = 'CLAIM_MINTED_AIRDROPS',

  AWARD_CREATE = 'AWARD_CREATE',
  AWARD_FUND = 'AWARD_FUND',
  AWARD_APPROVE_PARTICIPANT = 'AWARD_APPROVE_PARTICIPANT',

  PROPOSAL_CREATE = 'PROPOSAL_CREATE',
  PROPOSAL_APPROVE = 'PROPOSAL_APPROVE',
  PROPOSAL_REJECT = 'PROPOSAL_REJECT',
  PROPOSAL_VOTE = 'PROPOSAL_VOTE',
}
