/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgAirdrop extends commons.BaseRecord {
  member?: string;
  token?: string;
  award?: string;
  vestingAt?: Date;
  count?: number;
  status?: string;
  orderId?: string;
  billPaymentId?: string;
  sourceAddress?: string;
  stakeRewardId?: string;
  stakeType?: string;
  isBaseToken?: boolean;
}
