/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgAuctionUpdate extends commons.BaseRecordUpdate {
  space?: string | null;
  auctionFrom?: Date | null;
  auctionTo?: Date | null;
  auctionLength?: number | null | Increment;
  extendedAuctionTo?: Date | null;
  extendedAuctionLength?: number | null | Increment;
  extendAuctionWithin?: number | null | Increment;
  auctionFloorPrice?: number | null | Increment;
  minimalBidIncrement?: number | null | Increment;
  auctionHighestBidder?: string | null;
  auctionHighestBid?: number | null | Increment;
  maxBids?: number | null | Increment;
  type?: string | null;
  network?: string | null;
  nftId?: string | null;
  targetAddress?: string | null;
  active?: boolean | null;
  topUpBased?: boolean | null;
  bids?: string | null;
}
