/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgAwardParticipantsUpdate extends commons.BaseSubRecordUpdate {
  comment?: string | null;
  completed?: boolean | null;
  count?: number | null | Increment;
  tokenReward?: number | null | Increment;
}

export interface PgAwardOwnersUpdate extends commons.BaseSubRecordUpdate {}

export interface PgAwardUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  description?: string | null;
  space?: string | null;
  endDate?: Date | null;
  issued?: number | null | Increment;
  badgesMinted?: number | null | Increment;
  approved?: boolean | null;
  rejected?: boolean | null;
  completed?: boolean | null;
  network?: string | null;
  aliasStorageDeposit?: number | null | Increment;
  collectionStorageDeposit?: number | null | Increment;
  nttStorageDeposit?: number | null | Increment;
  nativeTokenStorageDeposit?: number | null | Increment;
  funded?: boolean | null;
  fundingAddress?: string | null;
  fundedBy?: string | null;
  address?: string | null;
  airdropClaimed?: number | null | Increment;
  aliasBlockId?: string | null;
  aliasId?: string | null;
  collectionBlockId?: string | null;
  collectionId?: string | null;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  isLegacy?: boolean | null;
  badge_name?: string | null;
  badge_description?: string | null;
  badge_total?: number | null | Increment;
  badge_type?: string | null;
  badge_tokenReward?: number | null | Increment;
  badge_tokenUid?: string | null;
  badge_tokenId?: string | null;
  badge_tokenSymbol?: string | null;
  badge_image?: string | null;
  badge_ipfsMedia?: string | null;
  badge_ipfsMetadata?: string | null;
  badge_ipfsRoot?: string | null;
  badge_lockTime?: number | null | Increment;
}
