/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common_update';

export interface PgChangesUpdate extends commons.BaseRecordUpdate {
  change?: string | any | null;
}
