/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgChanges extends commons.BaseRecord {
  change?: Record<string, unknown>;
}
