/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgCollectionVotesUpdate extends commons.BaseSubRecordUpdate {
  direction?: number | null | Increment;
}

export interface PgCollectionStatsUpdate extends commons.BaseSubRecordUpdate {
  votes_upvotes?: number | null | Increment;
  votes_downvotes?: number | null | Increment;
  votes_voteDiff?: number | null | Increment;
  ranks_count?: number | null | Increment;
  ranks_sum?: number | null | Increment;
  ranks_avg?: number | null | Increment;
}

export interface PgCollectionRanksUpdate extends commons.BaseSubRecordUpdate {
  rank?: number | null | Increment;
}

export interface PgCollectionUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  description?: string | null;
  bannerUrl?: string | null;
  royaltiesFee?: number | null | Increment;
  royaltiesSpace?: string | null;
  total?: number | null | Increment;
  totalTrades?: number | null | Increment;
  lastTradedOn?: Date | null;
  sold?: number | null | Increment;
  discord?: string | null;
  url?: string | null;
  twitter?: string | null;
  approved?: boolean | null;
  rejected?: boolean | null;
  limitedEdition?: boolean | null;
  ipfsMedia?: string | null;
  ipfsMetadata?: string | null;
  ipfsRoot?: string | null;
  category?: string | null;
  type?: number | null | Increment;
  access?: number | null | Increment;
  accessAwards?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  accessCollections?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  space?: string | null;
  availableFrom?: Date | null;
  price?: number | null | Increment;
  availablePrice?: number | null | Increment;
  onePerMemberOnly?: boolean | null;
  placeholderNft?: string | null;
  placeholderUrl?: string | null;
  status?: string | null;
  mintingData_address?: string | null;
  mintingData_network?: string | null;
  mintingData_mintedOn?: Date | null;
  mintingData_mintedBy?: string | null;
  mintingData_blockId?: string | null;
  mintingData_nftId?: string | null;
  mintingData_storageDeposit?: number | null | Increment;
  mintingData_aliasBlockId?: string | null;
  mintingData_aliasId?: string | null;
  mintingData_aliasStorageDeposit?: number | null | Increment;
  mintingData_mintingOrderId?: string | null;
  mintingData_nftsToMint?: number | null | Increment;
  mintingData_nftMediaToUpload?: number | null | Increment;
  mintingData_nftMediaToPrepare?: number | null | Increment;
  mintingData_unsoldMintingOptions?: string | null;
  mintingData_newPrice?: number | null | Increment;
  mintingData_nftsStorageDeposit?: number | null | Increment;
  rankCount?: number | null | Increment;
  rankSum?: number | null | Increment;
  rankAvg?: number | null | Increment;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  stakedNft?: number | null | Increment;
  nftsOnSale?: number | null | Increment;
  nftsOnAuction?: number | null | Increment;
  availableNfts?: number | null | Increment;
  floorPrice?: number | null | Increment;
  votes_upvotes?: number | null | Increment;
  votes_downvotes?: number | null | Increment;
  votes_voteDiff?: number | null | Increment;
  discounts?: string | null;
}
