/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
export interface Update {}
export interface BaseRecordUpdate extends Update {
  project?: string;
  createdOn?: Date;
  updatedOn?: Date;
  createdBy?: string;
}
export interface BaseSubRecordUpdate extends Update, BaseRecordUpdate {
  parentId?: string;
}
