/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
export interface BaseRecord {
  uid: string;
  project?: string;
  createdOn?: Date;
  updatedOn?: Date;
  createdBy?: string;
}
export interface BaseSubRecord extends BaseRecord {
  parentId: string;
}
