/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgMember extends commons.BaseRecord {
  nonce?: string;
  name?: string;
  about?: string;
  avatarNft?: string;
  avatar?: string;
  discord?: string;
  twitter?: string;
  github?: string;
  smrAddress?: string;
  rmsAddress?: string;
  iotaAddress?: string;
  atoiAddress?: string;
  prevValidatedAddresses?: string[];
  tokenTradingFeePercentage?: number;
  tokenPurchaseFeePercentage?: number;
  awardsCompleted?: number;
  spaces?: Record<string, unknown>;
}
