/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgMemberUpdate extends commons.BaseRecordUpdate {
  nonce?: string | null;
  name?: string | null;
  about?: string | null;
  avatarNft?: string | null;
  avatar?: string | null;
  discord?: string | null;
  twitter?: string | null;
  github?: string | null;
  smrAddress?: string | null;
  rmsAddress?: string | null;
  iotaAddress?: string | null;
  atoiAddress?: string | null;
  prevValidatedAddresses?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  tokenTradingFeePercentage?: number | null | Increment;
  tokenPurchaseFeePercentage?: number | null | Increment;
  awardsCompleted?: number | null | Increment;
  spaces?: string | any | null;
}
