/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgMilestoneTransactionsUpdate extends commons.BaseSubRecordUpdate {
  PayloadSize?: number | null | Increment;
  blockId?: string | null;
  milestone?: number | null | Increment;
  payload?: string | any | null;
  processed?: boolean | null;
  processedOn?: Date | null;
}

export interface PgMilestoneSmrTransactionsUpdate extends commons.BaseSubRecordUpdate {
  PayloadSize?: number | null | Increment;
  blockId?: string | null;
  milestone?: number | null | Increment;
  payload?: string | any | null;
  processed?: boolean | null;
  processedOn?: Date | null;
}

export interface PgMilestoneSmrUpdate extends commons.BaseRecordUpdate {
  completed?: boolean | null;
  completedOn?: Date | null;
  listenerNodeId?: string | null;
  milestone?: number | null | Increment;
  milestoneTimestamp?: Date | null;
  trxConflictCount?: number | null | Increment;
  trxFailedCount?: number | null | Increment;
  trxValidCount?: number | null | Increment;
}

export interface PgMilestoneRmsT2TransactionsUpdate extends commons.BaseSubRecordUpdate {
  PayloadSize?: number | null | Increment;
  blockId?: string | null;
  milestone?: number | null | Increment;
  payload?: string | any | null;
  processed?: boolean | null;
  processedOn?: Date | null;
}

export interface PgMilestoneRmsT2Update extends commons.BaseRecordUpdate {
  completed?: boolean | null;
  completedOn?: Date | null;
  listenerNodeId?: string | null;
  milestone?: number | null | Increment;
  milestoneTimestamp?: Date | null;
  trxConflictCount?: number | null | Increment;
  trxFailedCount?: number | null | Increment;
  trxValidCount?: number | null | Increment;
}

export interface PgMilestoneUpdate extends commons.BaseRecordUpdate {
  completed?: boolean | null;
  completedOn?: Date | null;
  listenerNodeId?: string | null;
  milestone?: number | null | Increment;
  milestoneTimestamp?: Date | null;
  trxConflictCount?: number | null | Increment;
  trxFailedCount?: number | null | Increment;
  trxValidCount?: number | null | Increment;
}
