/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgMnemonic extends commons.BaseRecord {
  mnemonic?: string;
  network?: string;
  lockedBy?: string;
  consumedOutputIds?: string[];
  consumedNftOutputIds?: string[];
  consumedAliasOutputIds?: string[];
}
