/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgNftStake extends commons.BaseRecord {
  member?: string;
  space?: string;
  collection?: string;
  nft?: string;
  weeks?: number;
  expiresAt?: Date;
  expirationProcessed?: boolean;
  type?: string;
}

export interface PgNft extends commons.BaseRecord {
  name?: string;
  description?: string;
  collection?: string;
  owner?: string;
  isOwned?: boolean;
  media?: string;
  ipfsMedia?: string;
  ipfsMetadata?: string;
  ipfsRoot?: string;
  saleAccess?: number;
  saleAccessMembers?: string[];
  available?: number;
  availableFrom?: Date;
  auctionFrom?: Date;
  auctionTo?: Date;
  extendedAuctionTo?: Date;
  auctionHighestBid?: number;
  auctionHighestBidder?: string;
  price?: number;
  totalTrades?: number;
  lastTradedOn?: Date;
  availablePrice?: number;
  auctionFloorPrice?: number;
  auctionLength?: number;
  extendedAuctionLength?: number;
  extendAuctionWithin?: number;
  type?: number;
  space?: string;
  url?: string;
  approved?: boolean;
  rejected?: boolean;
  properties?: Record<string, unknown>;
  stats?: Record<string, unknown>;
  placeholderNft?: boolean;
  position?: number;
  locked?: boolean;
  lockedBy?: string;
  sold?: boolean;
  mintingData_address?: string;
  mintingData_network?: string;
  mintingData_mintedOn?: Date;
  mintingData_mintedBy?: string;
  mintingData_blockId?: string;
  mintingData_nftId?: string;
  mintingData_storageDeposit?: number;
  mintingData_aliasBlockId?: string;
  mintingData_aliasId?: string;
  mintingData_aliasStorageDeposit?: number;
  mintingData_mintingOrderId?: string;
  mintingData_nftsToMint?: number;
  mintingData_nftMediaToUpload?: number;
  mintingData_nftMediaToPrepare?: number;
  mintingData_unsoldMintingOptions?: string;
  mintingData_newPrice?: number;
  mintingData_nftsStorageDeposit?: number;
  depositData_address?: string;
  depositData_network?: string;
  depositData_mintedOn?: Date;
  depositData_mintedBy?: string;
  depositData_blockId?: string;
  depositData_nftId?: string;
  depositData_storageDeposit?: number;
  depositData_aliasBlockId?: string;
  depositData_aliasId?: string;
  depositData_aliasStorageDeposit?: number;
  depositData_mintingOrderId?: string;
  depositData_nftsToMint?: number;
  depositData_nftMediaToUpload?: number;
  depositData_nftMediaToPrepare?: number;
  depositData_unsoldMintingOptions?: string;
  depositData_newPrice?: number;
  depositData_nftsStorageDeposit?: number;
  status?: string;
  hidden?: boolean;
  mediaStatus?: string;
  mediaUploadErrorCount?: number;
  soldOn?: Date;
  setAsAvatar?: boolean;
  auction?: string;
}
