/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgNftStakeUpdate extends commons.BaseRecordUpdate {
  member?: string | null;
  space?: string | null;
  collection?: string | null;
  nft?: string | null;
  weeks?: number | null | Increment;
  expiresAt?: Date | null;
  expirationProcessed?: boolean | null;
  type?: string | null;
}

export interface PgNftUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  description?: string | null;
  collection?: string | null;
  owner?: string | null;
  isOwned?: boolean | null;
  media?: string | null;
  ipfsMedia?: string | null;
  ipfsMetadata?: string | null;
  ipfsRoot?: string | null;
  saleAccess?: number | null | Increment;
  saleAccessMembers?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  available?: number | null | Increment;
  availableFrom?: Date | null;
  auctionFrom?: Date | null;
  auctionTo?: Date | null;
  extendedAuctionTo?: Date | null;
  auctionHighestBid?: number | null | Increment;
  auctionHighestBidder?: string | null;
  price?: number | null | Increment;
  totalTrades?: number | null | Increment;
  lastTradedOn?: Date | null;
  availablePrice?: number | null | Increment;
  auctionFloorPrice?: number | null | Increment;
  auctionLength?: number | null | Increment;
  extendedAuctionLength?: number | null | Increment;
  extendAuctionWithin?: number | null | Increment;
  type?: number | null | Increment;
  space?: string | null;
  url?: string | null;
  approved?: boolean | null;
  rejected?: boolean | null;
  properties?: string | any | null;
  stats?: string | any | null;
  placeholderNft?: boolean | null;
  position?: number | null | Increment;
  locked?: boolean | null;
  lockedBy?: string | null;
  sold?: boolean | null;
  mintingData_address?: string | null;
  mintingData_network?: string | null;
  mintingData_mintedOn?: Date | null;
  mintingData_mintedBy?: string | null;
  mintingData_blockId?: string | null;
  mintingData_nftId?: string | null;
  mintingData_storageDeposit?: number | null | Increment;
  mintingData_aliasBlockId?: string | null;
  mintingData_aliasId?: string | null;
  mintingData_aliasStorageDeposit?: number | null | Increment;
  mintingData_mintingOrderId?: string | null;
  mintingData_nftsToMint?: number | null | Increment;
  mintingData_nftMediaToUpload?: number | null | Increment;
  mintingData_nftMediaToPrepare?: number | null | Increment;
  mintingData_unsoldMintingOptions?: string | null;
  mintingData_newPrice?: number | null | Increment;
  mintingData_nftsStorageDeposit?: number | null | Increment;
  depositData_address?: string | null;
  depositData_network?: string | null;
  depositData_mintedOn?: Date | null;
  depositData_mintedBy?: string | null;
  depositData_blockId?: string | null;
  depositData_nftId?: string | null;
  depositData_storageDeposit?: number | null | Increment;
  depositData_aliasBlockId?: string | null;
  depositData_aliasId?: string | null;
  depositData_aliasStorageDeposit?: number | null | Increment;
  depositData_mintingOrderId?: string | null;
  depositData_nftsToMint?: number | null | Increment;
  depositData_nftMediaToUpload?: number | null | Increment;
  depositData_nftMediaToPrepare?: number | null | Increment;
  depositData_unsoldMintingOptions?: string | null;
  depositData_newPrice?: number | null | Increment;
  depositData_nftsStorageDeposit?: number | null | Increment;
  status?: string | null;
  hidden?: boolean | null;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  soldOn?: Date | null;
  setAsAvatar?: boolean | null;
  auction?: string | null;
}
