/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgNotification extends commons.BaseRecord {
  space?: string;
  member?: string;
  type?: string;
  params?: Record<string, unknown>;
}
