/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common_update';

export interface PgNotificationUpdate extends commons.BaseRecordUpdate {
  space?: string | null;
  member?: string | null;
  type?: string | null;
  params?: string | any | null;
}
