/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common_update';

export interface PgProjectAdminsUpdate extends commons.BaseSubRecordUpdate {}

export interface PgProjectApiKeyUpdate extends commons.BaseSubRecordUpdate {
  token?: string | null;
}

export interface PgProjectUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  contactEmail?: string | null;
  deactivated?: boolean | null;
  config_billing?: string | null;
  config_tiers?: number[] | null;
  config_tokenTradingFeeDiscountPercentage?: number[] | null;
  config_nativeTokenSymbol?: string | null;
  config_nativeTokenUid?: string | null;
  otr?: string | any | null;
}
