/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgProjectAdmins extends commons.BaseSubRecord {}

export interface PgProjectApiKey extends commons.BaseSubRecord {
  token?: string;
}

export interface PgProject extends commons.BaseRecord {
  name?: string;
  contactEmail?: string;
  deactivated?: boolean;
  config_billing?: string;
  config_tiers?: number[];
  config_tokenTradingFeeDiscountPercentage?: number[];
  config_nativeTokenSymbol?: string;
  config_nativeTokenUid?: string;
  otr?: Record<string, unknown>;
}
