/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgProposalOwners extends commons.BaseSubRecord {}

export interface PgProposalMembers extends commons.BaseSubRecord {
  voted?: boolean;
  weight?: number;
  tranId?: string;
  values?: Record<string, unknown>;
}

export interface PgProposal extends commons.BaseRecord {
  space?: string;
  name?: string;
  description?: string;
  additionalInfo?: string;
  type?: number;
  approved?: boolean;
  rejected?: boolean;
  approvedBy?: string;
  rejectedBy?: string;
  eventId?: string;
  totalWeight?: number;
  token?: string;
  completed?: boolean;
  rank?: number;
  settings_startDate?: Date;
  settings_endDate?: Date;
  settings_guardiansOnly?: boolean;
  settings_addRemoveGuardian?: string;
  settings_spaceUpdateData?: Record<string, unknown>;
  settings_onlyGuardians?: boolean;
  settings_stakeRewardIds?: string[];
  settings_awards?: string[];
  questions?: Record<string, unknown>[];
  members?: Record<string, unknown>[];
  results?: Record<string, unknown>;
}
