/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgProposalOwnersUpdate extends commons.BaseSubRecordUpdate {}

export interface PgProposalMembersUpdate extends commons.BaseSubRecordUpdate {
  voted?: boolean | null;
  weight?: number | null | Increment;
  tranId?: string | null;
  values?: string | any | null;
}

export interface PgProposalUpdate extends commons.BaseRecordUpdate {
  space?: string | null;
  name?: string | null;
  description?: string | null;
  additionalInfo?: string | null;
  type?: number | null | Increment;
  approved?: boolean | null;
  rejected?: boolean | null;
  approvedBy?: string | null;
  rejectedBy?: string | null;
  eventId?: string | null;
  totalWeight?: number | null | Increment;
  token?: string | null;
  completed?: boolean | null;
  rank?: number | null | Increment;
  settings_startDate?: Date | null;
  settings_endDate?: Date | null;
  settings_guardiansOnly?: boolean | null;
  settings_addRemoveGuardian?: string | null;
  settings_spaceUpdateData?: string | any | null;
  settings_onlyGuardians?: boolean | null;
  settings_stakeRewardIds?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  settings_awards?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  questions?: string | null;
  members?: string | null;
  results?: string | any | null;
}
