/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgSoonSnapshotUpdate extends commons.BaseRecordUpdate {
  count?: number | null | Increment;
  paidOut?: number | null | Increment;
  lastPaidOutOn?: Date | null;
  ethAddress?: string | null;
  ethAddressVerified?: boolean | null;
}
