/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgSpaceMembersUpdate extends commons.BaseSubRecordUpdate {}

export interface PgSpaceKnockingmembersUpdate extends commons.BaseSubRecordUpdate {}

export interface PgSpaceGuardiansUpdate extends commons.BaseSubRecordUpdate {}

export interface PgSpaceBlockedmembersUpdate extends commons.BaseSubRecordUpdate {}

export interface PgSpaceUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  about?: string | null;
  open?: boolean | null;
  tokenBased?: boolean | null;
  minStakedValue?: number | null | Increment;
  github?: string | null;
  twitter?: string | null;
  discord?: string | null;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
  totalGuardians?: number | null | Increment;
  totalMembers?: number | null | Increment;
  totalPendingMembers?: number | null | Increment;
  smrAddress?: string | null;
  rmsAddress?: string | null;
  iotaAddress?: string | null;
  atoiAddress?: string | null;
  prevValidatedAddresses?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  vaultAddress?: string | null;
  collectionId?: string | null;
  claimed?: boolean | null;
  ipfsMedia?: string | null;
  ipfsMetadata?: string | null;
  ipfsRoot?: string | null;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  alias_address?: string | null;
  alias_aliasId?: string | null;
  alias_blockId?: string | null;
  alias_mintedOn?: Date | null;
  alias_mintedBy?: string | null;
}
