/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgStakeReward extends commons.BaseRecord {
  startDate?: Date;
  endDate?: Date;
  tokenVestingDate?: Date;
  tokensToDistribute?: number;
  token?: string;
  totalStaked?: number;
  totalAirdropped?: number;
  status?: string;
}

export interface PgStake extends commons.BaseRecord {
  member?: string;
  space?: string;
  token?: string;
  amount?: number;
  value?: number;
  weeks?: number;
  expiresAt?: Date;
  expirationProcessed?: boolean;
  orderId?: string;
  billPaymentId?: string;
  type?: string;
  customMetadata?: Record<string, unknown>;
}
