/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgStamp extends commons.BaseRecord {
  space?: string;
  buildcoreUrl?: string;
  originUri?: string;
  checksum?: string;
  extension?: string;
  bytes?: number;
  costPerMb?: number;
  network?: string;
  ipfsMedia?: string;
  ipfsRoot?: string;
  expiresAt?: Date;
  order?: string;
  funded?: boolean;
  expired?: boolean;
  mediaStatus?: string;
  mediaUploadErrorCount?: number;
  aliasId?: string;
  nftId?: string;
}
