/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgStampUpdate extends commons.BaseRecordUpdate {
  space?: string | null;
  buildcoreUrl?: string | null;
  originUri?: string | null;
  checksum?: string | null;
  extension?: string | null;
  bytes?: number | null | Increment;
  costPerMb?: number | null | Increment;
  network?: string | null;
  ipfsMedia?: string | null;
  ipfsRoot?: string | null;
  expiresAt?: Date | null;
  order?: string | null;
  funded?: boolean | null;
  expired?: boolean | null;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  aliasId?: string | null;
  nftId?: string | null;
}
