/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgSwap extends commons.BaseRecord {
  recipient?: string;
  network?: string;
  address?: string;
  orderId?: string;
  nftIdsAsk?: string[];
  baseTokenAmountAsk?: number;
  nativeTokensAsk?: Record<string, unknown>[];
  status?: string;
  bidOutputs?: Record<string, unknown>[];
  askOutputs?: Record<string, unknown>[];
}
