/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgSwapUpdate extends commons.BaseRecordUpdate {
  recipient?: string | null;
  network?: string | null;
  address?: string | null;
  orderId?: string | null;
  nftIdsAsk?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  baseTokenAmountAsk?: number | null | Increment;
  nativeTokensAsk?: string | null;
  status?: string | null;
  bidOutputs?: string | null;
  askOutputs?: string | null;
}
