/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgSystemUpdate extends commons.BaseRecordUpdate {
  tokenTradingFeePercentage?: number | null | Increment;
  tokenPurchaseFeePercentage?: number | null | Increment;
}
