/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import * as commons from './common';

export interface PgSystem extends commons.BaseRecord {
  tokenTradingFeePercentage?: number;
  tokenPurchaseFeePercentage?: number;
}
