/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgTickerUpdate extends commons.BaseRecordUpdate {
  price?: number | null | Increment;
}
