/**
 * This file was automatically generated by knex
 * Do not modify this file manually
 */
import { ArrayRemove, ArrayUnion, Increment } from '../interfaces/common';
import * as commons from './common_update';

export interface PgTokenVotesUpdate extends commons.BaseSubRecordUpdate {
  direction?: number | null | Increment;
}

export interface PgTokenStatsUpdate extends commons.BaseSubRecordUpdate {
  votes_upvotes?: number | null | Increment;
  votes_downvotes?: number | null | Increment;
  votes_voteDiff?: number | null | Increment;
  ranks_count?: number | null | Increment;
  ranks_sum?: number | null | Increment;
  ranks_avg?: number | null | Increment;
  volumeTotal?: number | null | Increment;
  volume_in24h?: number | null | Increment;
  volume_in48h?: number | null | Increment;
  volume_in7d?: number | null | Increment;
  stakes_static_amount?: number | null | Increment;
  stakes_static_totalAmount?: number | null | Increment;
  stakes_static_value?: number | null | Increment;
  stakes_static_totalValue?: number | null | Increment;
  stakes_static_stakingMembersCount?: number | null | Increment;
  stakes_dynamic_amount?: number | null | Increment;
  stakes_dynamic_totalAmount?: number | null | Increment;
  stakes_dynamic_value?: number | null | Increment;
  stakes_dynamic_totalValue?: number | null | Increment;
  stakes_dynamic_stakingMembersCount?: number | null | Increment;
  stakeExpiry?: string | any | null;
}

export interface PgTokenRanksUpdate extends commons.BaseSubRecordUpdate {
  rank?: number | null | Increment;
}

export interface PgTokenPurchaseUpdate extends commons.BaseRecordUpdate {
  token?: string | null;
  tokenStatus?: string | null;
  sell?: string | null;
  buy?: string | null;
  count?: number | null | Increment;
  price?: number | null | Increment;
  triggeredBy?: string | null;
  billPaymentId?: string | null;
  buyerBillPaymentId?: string | null;
  royaltyBillPayments?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  sourceNetwork?: string | null;
  targetNetwork?: string | null;
  sellerTokenTradingFeePercentage?: number | null | Increment;
  sellerTier?: number | null | Increment;
  in24h?: boolean | null;
  in48h?: boolean | null;
  in7d?: boolean | null;
}

export interface PgTokenMarketUpdate extends commons.BaseRecordUpdate {
  owner?: string | null;
  token?: string | null;
  tokenStatus?: string | null;
  type?: string | null;
  count?: number | null | Increment;
  price?: number | null | Increment;
  totalDeposit?: number | null | Increment;
  balance?: number | null | Increment;
  fulfilled?: number | null | Increment;
  status?: string | null;
  orderTransactionId?: string | null;
  paymentTransactionId?: string | null;
  creditTransactionId?: string | null;
  expiresAt?: Date | null;
  shouldRetry?: boolean | null;
  sourceNetwork?: string | null;
  targetNetwork?: string | null;
  targetAddress?: string | null;
}

export interface PgTokenDistributionUpdate extends commons.BaseSubRecordUpdate {
  totalDeposit?: number | null | Increment;
  totalPaid?: number | null | Increment;
  refundedAmount?: number | null | Increment;
  totalBought?: number | null | Increment;
  reconciled?: boolean | null;
  billPaymentId?: string | null;
  creditPaymentId?: string | null;
  royaltyBillPaymentId?: string | null;
  tokenClaimed?: number | null | Increment;
  lockedForSale?: number | null | Increment;
  sold?: number | null | Increment;
  totalPurchased?: number | null | Increment;
  tokenOwned?: number | null | Increment;
  mintedClaimedOn?: Date | null;
  mintingTransactions?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  stakeRewards?: number | null | Increment;
  extraStakeRewards?: number | null | Increment;
  totalUnclaimedAirdrop?: number | null | Increment;
  stakeVoteTransactionId?: string | null;
  stakes_static_amount?: number | null | Increment;
  stakes_static_totalAmount?: number | null | Increment;
  stakes_static_value?: number | null | Increment;
  stakes_static_totalValue?: number | null | Increment;
  stakes_static_stakingMembersCount?: number | null | Increment;
  stakes_dynamic_amount?: number | null | Increment;
  stakes_dynamic_totalAmount?: number | null | Increment;
  stakes_dynamic_value?: number | null | Increment;
  stakes_dynamic_totalValue?: number | null | Increment;
  stakes_dynamic_stakingMembersCount?: number | null | Increment;
  stakeExpiry?: string | any | null;
}

export interface PgTokenUpdate extends commons.BaseRecordUpdate {
  name?: string | null;
  symbol?: string | null;
  title?: string | null;
  description?: string | null;
  shortDescriptionTitle?: string | null;
  shortDescription?: string | null;
  space?: string | null;
  pricePerToken?: number | null | Increment;
  totalSupply?: number | null | Increment;
  allocations?: string | null;
  saleStartDate?: Date | null;
  saleLength?: number | null | Increment;
  coolDownEnd?: Date | null;
  autoProcessAt100Percent?: boolean | null;
  approved?: boolean | null;
  rejected?: boolean | null;
  public?: boolean | null;
  links?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  icon?: string | null;
  overviewGraphics?: string | null;
  status?: string | null;
  totalDeposit?: number | null | Increment;
  tokensOrdered?: number | null | Increment;
  totalAirdropped?: number | null | Increment;
  termsAndConditions?: string | null;
  access?: number | null | Increment;
  accessAwards?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  accessCollections?: string[] | null | ArrayUnion<string> | ArrayRemove<string>;
  ipfsMedia?: string | null;
  ipfsMetadata?: string | null;
  ipfsRoot?: string | null;
  mintingData_mintedBy?: string | null;
  mintingData_mintedOn?: Date | null;
  mintingData_aliasBlockId?: string | null;
  mintingData_aliasId?: string | null;
  mintingData_aliasStorageDeposit?: number | null | Increment;
  mintingData_tokenId?: string | null;
  mintingData_blockId?: string | null;
  mintingData_foundryStorageDeposit?: number | null | Increment;
  mintingData_network?: string | null;
  mintingData_networkFormat?: string | null;
  mintingData_vaultAddress?: string | null;
  mintingData_tokensInVault?: number | null | Increment;
  mintingData_vaultStorageDeposit?: number | null | Increment;
  mintingData_guardianStorageDeposit?: number | null | Increment;
  mintingData_meltedTokens?: number | null | Increment;
  mintingData_circulatingSupply?: number | null | Increment;
  rankCount?: number | null | Increment;
  rankSum?: number | null | Increment;
  rankAvg?: number | null | Increment;
  mediaStatus?: string | null;
  mediaUploadErrorCount?: number | null | Increment;
  tradingDisabled?: boolean | null;
  decimals?: number | null | Increment;
  votes_upvotes?: number | null | Increment;
  votes_downvotes?: number | null | Increment;
  votes_voteDiff?: number | null | Increment;
}
