/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a bid order.
 */
export interface AuctionBidRequest {
  /**
   * Build5 id of the auction.
   */
  auction: string;
}
