/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Object representing a badge
 */
export interface AwardCreateBadgeRequest {
  /**
   * Description of the badge
   */
  description?: string | null | '';
  /**
   * An https url pointing to a soonaverse image.
   */
  image: string;
  /**
   * The time for which the reward nft will be locked.
   */
  lockTime: number;
  /**
   * Name of the badge
   */
  name: string;
  /**
   * The amount of token rewarded with this badge.
   */
  tokenReward: number;
  /**
   * The symbol of the reward token.
   */
  tokenSymbol: string;
  /**
   * Total noumber of bages that can be issued. Minimum 1, maximum 10000
   */
  total: number;
}

/**
 * Request object to create an award
 */
export interface AwardCreateRequest {
  /**
   * Object representing a badge
   */
  badge?: AwardCreateBadgeRequest;
  /**
   * Description of the award
   */
  description?: string | null | '';
  /**
   * End date of the award issuing period.
   */
  endDate: Date;
  /**
   * Name of the award
   */
  name: string;
  /**
   * Network on which the award will be minted and issued
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Build5 id of the space
   */
  space: string;
}
