/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a collection mint order.
 */
export interface CollectionMintRequest {
  /**
   * Build5 id of the collection to mint.
   */
  collection: string;
  /**
   * Network to use for minting the collection.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Price in case unsold minting option is set to new price. Minimum 1000000, maximum 1000000000000
   */
  price?: number;
  /**
   * Specifies what should happen with unsold NFTs in this collection.
   */
  unsoldMintingOptions: 'burn_unsold' | 'set_new_price' | 'keep_price' | 'take_ownership';
}
