/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to approve a collection.
 */
export interface ApproveCollectionRequest {
  /**
   * Build5 id of the collection.
   */
  uid: string;
}
