/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a member
 */
export interface CreateMemberRequest {
  /**
   * Wallet address of the member
   */
  address: string;
}
