/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to upload a file.
 */
export interface FileUploadRequest {
  /**
   * Build5 id of the member.
   */
  member: string;
  /**
   * Mime type of the file
   */
  mimeType: string;
  /**
   * Id for the file.
   */
  uid: string;
}
