/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to set an NFT for sale.
 */
export interface NftSetForSaleRequest {
  /**
   * Access type of this sale.
   */
  access?: 0 | 1;
  /**
   * If present, members who can buy this nft
   */
  accessMembers?: any[];
  /**
   * Floor price of the nft. Minimum 1000000, maximum 1000000000000
   */
  auctionFloorPrice?: number;
  /**
   * Starting date of the nft's auction. Can not be sooner then 10 minutes.
   */
  auctionFrom?: Date;
  /**
   * Millisecond value of the auction length. Minimum 240000, maximum 2678400000
   */
  auctionLength?: number;
  /**
   * Starting date of the nft's availability. Can not be sooner then 10 minutes.
   */
  availableFrom?: Date;
  /**
   * Auction will be extended if a bid happens this many milliseconds before auction ends. Default value is 300000 minutes
   */
  extendAuctionWithin?: number;
  /**
   * If set, auction will automatically extended by this length if a bid comes in within {@link extendAuctionWithin} before the end of the auction.
   */
  extendedAuctionLength?: number;
  /**
   * Defines the minimum increment of a subsequent bid. Minimum 1000000, maximum 1000000000000
   */
  minimalBidIncrement?: number;
  /**
   * Build5 id of the nft.
   */
  nft: string;
  /**
   * Price of the nft. Minimum 1000000, maximum 1000000000000
   */
  price?: number;
}
