/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to join a space.
 */
export interface SpaceJoinRequest {
  /**
   * Build5 id of the space.
   */
  uid: string;
}
