/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a token purchase order.
 */
export interface OrderTokenRequest {
  /**
   * Build5 id of the token
   */
  token: string;
}
