/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to cancel token public sale.
 */
export interface CanelPublicSaleRequest {
  /**
   * Build5 id of the token.
   */
  token: string;
}
