/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to enable token trading.
 */
export interface EnableTokenTradingRequest {
  /**
   * Build5 id of the token.
   */
  uid: string;
}
