/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to claim minted tokens.
 */
export interface ClaimAirdroppedTokensRequest {
  /**
   * Symbol of the token to claim.
   */
  symbol: string;
}
