/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to vote an entity.
 */
export interface VoteRequest {
  /**
   * Build5 collection to vote on.
   */
  collection: 'collection' | 'token';
  /**
   * Direction of the vote.
   */
  direction: -1 | 0 | 1;
  /**
   * Build5 id of the entity to vote on.
   */
  uid: string;
}
