/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to validate an address. If the source address is SMR, the address will be validated, otherswise and address validation order is created.
 */
export interface AddressValidationTangleRequest {
  /**
   * Network to use for the address
   */
  network?: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Type of the tangle request.
   */
  requestType: 'ADDRESS_VALIDATION';
  /**
   * Build5 id of the space
   */
  space?: string;
}
