/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create an award
 */
export interface AwardCreateTangleRequest {
  badge?: {
    /**
     * Description of the badge
     */
    description?: string | null | '';
    image?: string;
    /**
     * The time for wich the reward nft will be locked.
     */
    lockTime: number;
    /**
     * Name of the badge
     */
    name: string;
    /**
     * The amount of token rewarded with this badge.
     */
    tokenReward: number;
    /**
     * The symbol of the reward token.
     */
    tokenSymbol: string;
    /**
     * Total noumber of bages that can be issued. Minimum 1, maximum 10000
     */
    total: number;
  };
  /**
   * Description of the award
   */
  description?: string | null | '';
  /**
   * End date of the award issuing period.
   */
  endDate: Date;
  /**
   * Name of the award
   */
  name: string;
  /**
   * Network on wich the award will be minted and issued
   */
  network: 'smr' | 'rms';
  /**
   * Type of the tangle request.
   */
  requestType:
    | 'ADDRESS_VALIDATION'
    | 'SELL_TOKEN'
    | 'BUY_TOKEN'
    | 'STAKE'
    | 'NFT_PURCHASE'
    | 'NFT_BID'
    | 'CLAIM_MINTED_AIRDROPS'
    | 'AWARD_CREATE'
    | 'AWARD_FUND'
    | 'AWARD_APPROVE_PARTICIPANT'
    | 'PROPOSAL_CREATE'
    | 'PROPOSAL_APPROVE'
    | 'PROPOSAL_REJECT'
    | 'PROPOSAL_VOTE'
    | 'SPACE_CREATE'
    | 'SPACE_JOIN'
    | 'SPACE_ADD_GUARDIAN'
    | 'SPACE_REMOVE_GUARDIAN'
    | 'SPACE_ACCEPT_MEMBER'
    | 'SPACE_BLOCK_MEMBER'
    | 'SPACE_DECLINE_MEMBER'
    | 'SPACE_LEAVE'
    | 'MINT_METADATA_NFT';
  /**
   * Build5 id of the space
   */
  space: string;
}
