/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create or update a metadata nft.
 */
export interface MintMetadataNftTangleRequest {
  /**
   * Alias tangle id. The new nft will belong to this alias.
   */
  aliasId?: string;
  /**
   * Collection tangle id. The new nft will belong to this collection.
   */
  collectionId?: string;
  /**
   * Metadata object of for the nft.
   */
  metadata: object;
  /**
   * Nft network id. Only specify it in case of edit.
   */
  nftId?: string;
  /**
   * Type of the tangle request.
   */
  requestType: 'MINT_METADATA_NFT';
}
