/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create an NFT bid
 */
export interface NftBidTangleRequest {
  /**
   * If set to true, NFT will not be sent to the buyer's validated address upon purchase.
   */
  disableWithdraw?: boolean;
  /**
   * Build5 if of the nft to bid on.
   */
  nft: string;
  /**
   * Type of the tangle request.
   */
  requestType: 'NFT_BID';
}
