/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create a proposal
 */
export interface ProposalCreateTangleRequest {
  /**
   * Additional information about the proposal.
   */
  additionalInfo?: string | null | '';
  /**
   * Description of the proposal
   */
  description?: string | null | '';
  /**
   * Name of the proposal
   */
  name: string;
  questions: {
    additionalInfo?: string | null | '';
    answers: {
      additionalInfo?: string | null | '';
      text: string;
      value: number;
    }[];
    text: string;
  }[];
  /**
   * Type of the tangle request.
   */
  requestType:
    | 'ADDRESS_VALIDATION'
    | 'SELL_TOKEN'
    | 'BUY_TOKEN'
    | 'STAKE'
    | 'NFT_PURCHASE'
    | 'CLAIM_MINTED_AIRDROPS'
    | 'AWARD_CREATE'
    | 'AWARD_FUND'
    | 'AWARD_APPROVE_PARTICIPANT'
    | 'PROPOSAL_CREATE'
    | 'PROPOSAL_APPROVE'
    | 'PROPOSAL_REJECT'
    | 'PROPOSAL_VOTE'
    | 'SPACE_CREATE'
    | 'SPACE_JOIN'
    | 'SPACE_ADD_GUARDIAN'
    | 'SPACE_REMOVE_GUARDIAN'
    | 'SPACE_ACCEPT_MEMBER'
    | 'SPACE_BLOCK_MEMBER'
    | 'SPACE_DECLINE_MEMBER'
    | 'SPACE_LEAVE'
    | 'MINT_METADATA_NFT';
  /**
   * Settings object of the proposal
   */
  settings: {
    /**
     * End date of the proposal. Has to be after start date.
     */
    endDate: Date;
    /**
     * Set true if only guardians can vote on this proposal
     */
    onlyGuardians: boolean;
    /**
     * Starting date of the proposal. Has to be at least 300000 milliseconds in the future
     */
    startDate: Date;
  };
  /**
   * Build5 id of the space where the proposal should be created.
   */
  space: string;
  /**
   * Type of the proposal.
   */
  type: 1 | 0;
}
