/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create a space.
 */
export interface SpaceCreateTangleRequest {
  /**
   * Information about the space.
   */
  about?: string | null | '';
  /**
   * Avatar url of ths space
   */
  avatarUrl?: string | null | '';
  bannerUrl?: string;
  /**
   * Discord url of the space.
   */
  discord?: string | null | '';
  /**
   * Github url of ths space
   */
  github?: string | null | '';
  /**
   * Name of the space.
   */
  name?: string | null | '';
  /**
   * If true, anyone can instantly join this space.
   */
  open?: false | true;
  /**
   * Type of the tangle request.
   */
  requestType:
    | 'ADDRESS_VALIDATION'
    | 'SELL_TOKEN'
    | 'BUY_TOKEN'
    | 'STAKE'
    | 'NFT_PURCHASE'
    | 'NFT_BID'
    | 'CLAIM_MINTED_AIRDROPS'
    | 'AWARD_CREATE'
    | 'AWARD_FUND'
    | 'AWARD_APPROVE_PARTICIPANT'
    | 'PROPOSAL_CREATE'
    | 'PROPOSAL_APPROVE'
    | 'PROPOSAL_REJECT'
    | 'PROPOSAL_VOTE'
    | 'SPACE_CREATE'
    | 'SPACE_JOIN'
    | 'SPACE_ADD_GUARDIAN'
    | 'SPACE_REMOVE_GUARDIAN'
    | 'SPACE_ACCEPT_MEMBER'
    | 'SPACE_BLOCK_MEMBER'
    | 'SPACE_DECLINE_MEMBER'
    | 'SPACE_LEAVE'
    | 'MINT_METADATA_NFT';
  /**
   * Twitter url of ths space
   */
  twitter?: string | null | '';
}
