/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to edit a space member.
 */
export interface SpaceMemberUpsertTangleRequest {
  /**
   * Build5 id of the member
   */
  member: string;
  /**
   * Type of the tangle request.
   */
  requestType:
    | 'SPACE_ADD_GUARDIAN'
    | 'SPACE_REMOVE_GUARDIAN'
    | 'SPACE_ACCEPT_MEMBER'
    | 'SPACE_BLOCK_MEMBER'
    | 'SPACE_DECLINE_MEMBER';
  /**
   * Build5 id of the space
   */
  uid: string;
}
