/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to trade a token.
 */
export interface TradeTokenTangleRequest {
  /**
   * Pirce of the token to trade. Minimum 0.001, maximum: 1000000000000.
   */
  price: number;
  /**
   * Symbol of the token to trade.
   */
  symbol: string;
  /**
   * Direction of the trade.
   */
  type: 'sell' | 'buy';
}
