/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to claim airdropped tokens.
 */
export interface ClaimAirdroppedTokensTangleRequest {
  /**
   * Type of the tangle request.
   */
  requestType: 'CLAIM_MINTED_AIRDROPS';
  /**
   * Symbol of the token.
   */
  symbol: string;
}
