/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to trade a token.
 */
export interface TradeTokenTangleRequest {
  /**
   * Count of the tokens to be bought. Only specify is type is BUY. Minimum 1, maximum 1e+26
   */
  count?: number;
  /**
   * Pirce of the token to trade. Minimum 0.000001, maximum: 1000000000000.
   */
  price: number;
  /**
   * Type of the tangle request.
   */
  requestType:
    | 'ADDRESS_VALIDATION'
    | 'SELL_TOKEN'
    | 'BUY_TOKEN'
    | 'STAKE'
    | 'NFT_PURCHASE'
    | 'NFT_BID'
    | 'CLAIM_MINTED_AIRDROPS'
    | 'AWARD_CREATE'
    | 'AWARD_FUND'
    | 'AWARD_APPROVE_PARTICIPANT'
    | 'PROPOSAL_CREATE'
    | 'PROPOSAL_APPROVE'
    | 'PROPOSAL_REJECT'
    | 'PROPOSAL_VOTE'
    | 'SPACE_CREATE'
    | 'SPACE_JOIN'
    | 'SPACE_ADD_GUARDIAN'
    | 'SPACE_REMOVE_GUARDIAN'
    | 'SPACE_ACCEPT_MEMBER'
    | 'SPACE_BLOCK_MEMBER'
    | 'SPACE_DECLINE_MEMBER'
    | 'SPACE_LEAVE'
    | 'MINT_METADATA_NFT';
  /**
   * Symbol of the token to trade.
   */
  symbol: string;
  /**
   * Direction of the trade.
   */
  type: 'sell' | 'buy';
}
