/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create a token stake order.
 */
export interface TokenStakeTangleRequest {
  /**
   * Custom metadata object. It can have 5 field. 
For each field the name can be maximum 50 character long. 
For each field  the value can be 255 characters long.
   */
  customMetadata?: {
    /**
     * Unknown Property
     */
    [x: string]: unknown;
  };
  /**
   * Type of the tangle request.
   */
  requestType: 'STAKE';
  /**
   * Symbol of the token.
   */
  symbol: string;
  /**
   * Type of the stake.
   */
  type: 'static' | 'dynamic';
  /**
   * Amount of weeks for which the tokens will be staked. Minimum 1, maximum 52
   */
  weeks: number;
}
