/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create an address validation order
 */
export interface AddressValidationRequest {
  /**
   * Network to use for the address
   */
  network?: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Buildcore id of the space
   */
  space?: string;
}
