/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to reject an award
 */
export interface AwardRejectRequest {
  /**
   * Build5 id of the award.
   */
  uid: string;
}
