/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to cancel an award
 */
export interface AwardCancelRequest {
  /**
   * Buildcore id of the award.
   */
  uid: string;
}
