/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to add an owner for an existing award.
 */
export interface AwardAddOwnerRequest {
  /**
   * Buildcore id or wallet address of the member to be added as an owner.
   */
  member: string;
  /**
   * Buildcore id of the award.
   */
  uid: string;
}
