/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to partipate in an award
 */
export interface AwardParticpateRequest {
  /**
   * Reason for participation
   */
  comment?: string | null | '';
  /**
   * Build5 id of the award
   */
  uid: string;
}
