/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create an award fund order
 */
export interface AwardFundRequest {
  /**
   * Buildcore id of the award.
   */
  uid: string;
}
