/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to update a minted collection.
 */
export interface UpdateMintedCollectionRequest {
  /**
   * Access type of the collection.
   */
  access?: 0 | 1 | 2 | 3 | 4;
  /**
   * Build5 id of awards. If set, only members having the specified awards can access this collection.
   */
  accessAwards?: any[];
  /**
   * Build5 id of collections. If set, only members owning NFTs from the specified collection can access this collection.
   */
  accessCollections?: any[];
  /**
   * The collections available from data. It can be maximum 10 minutes in the past.
   */
  availableFrom?: Date;
  /**
   * Array of discounts. Minimum 0, maximum 5.
   */
  discounts?: {
    /**
     * Amount of the discount to be applied. Minimum 0.01, maximum 1.
     */
    amount: number;
    /**
     * Token amount to be rewarded, minimum 0. This must be unique.
     */
    tokenReward: number;
    /**
     * Symbol of the token.
     */
    tokenSymbol: string;
  }[];
  /**
   * If true, only on NFT can be owned per member from this collection.
   */
  onePerMemberOnly?: boolean;
  /**
   * Price of the collection. Minimum 1000000, maximum 1000000000000.
   */
  price?: number;
  /**
   * Build5 id of the collection.
   */
  uid: string;
}
