/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to reject a collection.
 */
export interface RejectCollectionRequest {
  /**
   * Build5 id of the collection.
   */
  uid: string;
}
