/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a refund order.
 */
export interface CreditUnrefundableRequest {
  /**
   * Build5 id of the transaction to be unlocked and credited back.
   */
  transaction: string;
}
