/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a custom login token. No params required.
 */
export interface CustomTokenRequest {}
