/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create an NFT bid order.
 */
export interface NftBidRequest {
  /**
   * Build5 id of the nft.
   */
  nft: string;
}
