/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create or update a metadata nft.
 */
export interface MintMetadataNftRequest {
  /**
   * Alias tangle id. The new nft will belong to this alias.
   */
  aliasId?: string;
  /**
   * Collection tangle id. The new nft will belong to this collection.
   */
  collectionId?: string;
  /**
   * Metadata object of for the nft.
   */
  metadata: object;
  /**
   * Network on which the NFT will be minted.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Nft network id. Only specify it in case of edit.
   */
  nftId?: string;
}
