/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { NftPurchaseRequest } from '.';

/**
 * Request object to create an NFT bulk purchase order
 */
export interface NftPurchaseBulkRequest {
  /**
   * List of collections&nfts to purchase, minimum 1, maximum 100
   */
  orders: NftPurchaseRequest[];
}
