/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create an NFT purchase order
 */
export interface NftPurchaseRequest {
  /**
   * Buildcore id of the collection in case a random nft is bought.
   */
  collection: string;
  /**
   * Buildcore id of the nft to be purchased.
   */
  nft?: string;
}
