/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to update an unsold NFT
 */
export interface NftUpdateUnsoldRequest {
  /**
   * Price of the nft. Minimum 1000000, maximum 1000000000000
   */
  price: number;
  /**
   * Build5 id of the nft to update
   */
  uid: string;
}
