/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to withdraw an NFT.
 */
export interface NftWithdrawRequest {
  /**
   * Buildcore id of the nft to withdraw.
   */
  nft: string;
}
