/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to deactivate a project.
 */
export interface ProjectDeactivateRequest {
  project: string;
}
