/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to approve a proposal
 */
export interface ApproveProposalRequest {
  /**
   * Buildcore id of the proposal to be approved.
   */
  uid: string;
}
