/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to reject a proposal
 */
export interface RejectProposalRequest {
  /**
   * Buildcore id of the proposal to be rejected.
   */
  uid: string;
}
