/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to vote on a proposal
 */
export interface ProposalVoteRequest {
  /**
   * Build5 id of the proposal to vote on.
   */
  uid: string;
  /**
   * Value of the vote.
   */
  value: number;
  /**
   * If true voting will be done with staked tokens.
   */
  voteWithStakedTokes?: boolean;
}
