/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to leave a space.
 */
export interface SpaceLeaveRequest {
  /**
   * Buildcore id of the space.
   */
  uid: string;
}
