/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to remove a stake reward(s).
 */
export interface TokenStakeRewardsRemoveRequest {
  /**
   * Build5 ids of the rewards to be removed
   */
  stakeRewardIds: string[];
}
