/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Object to create a stake reward.
 */
export interface TokenStakeRewardRequest {
  /**
   * End date of the reward in milliseconds. The base is current date.
   * Minimum 0, maximum 7978758988368, and it has to be after start date.
   */
  endDate: number;
  /**
   * Staring date of the reward in milliseconds. The base is current date.
   * Minimum 0, maximum 7978758988368
   */
  startDate: number;
  /**
   * Vesting time of the reward in milliseconds. The base is current date.
   * Minimum 0, maximum 7978758988368, and it has to be after end date.
   */
  tokenVestingDate: number;
  /**
   * Amount of tokens to be distributed with this reward. Minimum 1, maximum 1e+26
   */
  tokensToDistribute: number;
}

/**
 * Request object to create stake rewards.
 */
export interface TokenStakeRewardsRequest {
  /**
   * Stake reward items. Minimum 1, maximum 500.
   */
  items?: TokenStakeRewardRequest[];
  /**
   * Buildcore if of the token.
   */
  token: string;
}
