/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to stamp a file.
 */
export interface StampRequest {
  /**
   * Alias tangle id. The new nft will belong to this alias.
   */
  aliasId?: string;
  /**
   * Url for the file.
   */
  file: string;
  /**
   * Network to use to fund the stamp order.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
}
