/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a swap order.
 */
export interface SwapCreateRequest {
  /**
   * Requested base token amount
   */
  baseTokenAmount?: number;
  /**
   * Requested native token(s)
   */
  nativeTokens?: {
    amount: number;
    id: string;
  }[];
  /**
   * Network to use.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * List of requested Buildcore NFT ids or NFT tangle ids
   */
  nfts?: string[];
  /**
   * Target member Buildcore uid or tangle address
   */
  recipient: string;
}
