/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to reject a swap.
 */
export interface SwapRejectRequest {
  /**
   * Buildcore UID of the swap
   */
  uid: string;
}
