/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to set a swap as funded.
 */
export interface SwapSetFundedRequest {
  /**
   * Buildcore UID of the swap
   */
  uid: string;
}
