/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to update a minted token.
 */
export interface MintedTokenUpdateRequest {
  /**
   * Description of the token
   */
  description: string | null | '';
  /**
   * Links for the token
   */
  links?: string[];
  /**
   * Price per token. Minimum 0.000001, maximum 1000000000000.
   */
  pricePerToken?: number;
  /**
   * Short description of the token
   */
  shortDescription: string | null | '';
  /**
   * Short description title of the token
   */
  shortDescriptionTitle: string | null | '';
  /**
   * Title of the token
   */
  title: string | null | '';
  /**
   * Buildcore id of the token.
   */
  uid: string;
}

/**
 * Request object to update a token.
 */
export interface TokenUpdateRequest {
  /**
   * Description of the token
   */
  description: string | null | '';
  /**
   * Links for the token
   */
  links?: string[];
  /**
   * Name of the token
   */
  name: string | null | '';
  /**
   * Price per token. Minimum 0.000001, maximum 1000000000000.
   */
  pricePerToken?: number;
  /**
   * Short description of the token
   */
  shortDescription: string | null | '';
  /**
   * Short description title of the token
   */
  shortDescriptionTitle: string | null | '';
  /**
   * Title of the token
   */
  title: string | null | '';
  /**
   * Buildcore id of the token.
   */
  uid: string;
}
