/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a token import order.
 */
export interface ImportMintedTokenRequest {
  /**
   * Network name on which the token was minted.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Build5 space id to which the token should be associated with.
   */
  space: string;
  /**
   * Network id of the minted token.
   */
  tokenId: string;
}
