/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create a token trade order.
 */
export interface TradeTokenRequest {
  /**
   * Amount of tokens to be traded. Minimum 1, maximum 1e+26
   */
  count: number;
  /**
   * Price per token. Minimum 0.000001, maximum 1000000000000.
   */
  price: number;
  /**
   * Symbol of the token to trade.
   */
  symbol: string;
  /**
   * DIrection of the trade.
   */
  type: 'sell' | 'buy';
}
