/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to cancel a token trade order.
 */
export interface CancelTokenTradeOrderRequest {
  /**
   * Build5 id of the trade order.
   */
  uid: string;
}
