/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to claim airdrops.
 */
export interface ClaimPreMintedAirdroppedTokensRequest {
  /**
   * Buildcore id of the token.
   */
  token: string;
}
