/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to airdrop tokens.
 */
export interface CreateAirdropsRequest {
  /**
   * Array of airdrops
   */
  drops: {
    /**
     * Amount of tokens to be airdroped. Minimum 1, maximum 1e+26
     */
    count: number;
    /**
     * Buildcore id or wallet address of the recipient
     */
    recipient: string;
    /**
     * Type of the stake used for the airdrop
     */
    stakeType?: 'static' | 'dynamic';
    /**
     * Date when the airdrop will be vested.
     */
    vestingAt: Date;
  }[];
  /**
   * Buildcore id of the token
   */
  token: string;
}
