/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create an auction bid
 */
export interface AuctionBidTangleRequest {
  /**
   * Buildcore id of the auction to bid on.
   */
  auction: string;
  /**
   * Type of the tangle request.
   */
  requestType: 'BID_AUCTION';
}
