/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Request object to create an auction.
 */
export interface AuctionCreateTangleRequest {
  /**
   * Floor price of the auction. Minimum 1000000, maximum 1000000000000
   */
  auctionFloorPrice: number;
  /**
   * Starting date of the auction. Can not be sooner then 10 minutes.
   */
  auctionFrom: Date;
  /**
   * Millisecond value of the auction length. Minimum 240000, maximum 2678400000
   */
  auctionLength: number;
  /**
   * Auction will be extended if a bid happens this many milliseconds before auction ends. Default value is 300000 minutes
   */
  extendAuctionWithin?: number;
  /**
   * If set, auction will automatically extended by this length if a bid comes in within {@link extendAuctionWithin} before the end of the auction.
   */
  extendedAuctionLength?: number;
  /**
   * Specifies the maximum number of active bids. Minimum 1, maximum 10
   */
  maxBids: number;
  /**
   * Defines the minimum increment of a subsequent bid. Minimum 1000000, maximum 1000000000000
   */
  minimalBidIncrement?: number;
  /**
   * Network on which this auction accepts bids.
   */
  network: 'iota' | 'smr' | 'atoi' | 'rms';
  /**
   * Type of the tangle request.
   */
  requestType: 'CREATE_AUCTION';
  /**
   * Buildcore id of the space
   */
  space: string;
  /**
   * A valid network address where funds will be sent.
   */
  targetAddress?: string;
  /**
   * If set to true, consequent bids from the same user will be treated as topups
   */
  topUpBased?: boolean;
}
