/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to fund an award
 */
export interface AwardFundTangleRequest {
  /**
   * Type of the tangle request.
   */
  requestType: 'AWARD_FUND';
  /**
   * Build5 id of the award.
   */
  uid: string;
}
