/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create an NFT bulk purchase order
 */
export interface NftPurchaseBulkTangleRequest {
  /**
   * If set to true, NFT will not be sent to the buyer's validated address upon purchase.
   */
  disableWithdraw?: boolean;
  /**
   * List of collections&nfts to purchase, minimum 1, maximum 100
   */
  orders: {
    /**
     * Build5 id of the collection in case a random nft is bought.
     */
    collection: string;
    /**
     * Build5 id of the nft to be purchased.
     */
    nft?: string;
  }[];
  /**
   * Type of the tangle request.
   */
  requestType: 'NFT_PURCHASE_BULK';
}
