/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to transfer NFTs
 */
export interface NftTransferTangleRequest {
  /**
   * Type of the tangle request.
   */
  requestType: 'NFT_TRANSFER';
  /**
   * Provide list of NFTs to transfer to targetAddress or member id. Minimum 1, maximum 100
   */
  transfers: {
    /**
     * Buildcore id or tangle id of the nft.
     */
    nft: string;
    /**
     * Buildcore id of a member or a tangle address.
     */
    target: string;
    /**
     * If set, NFT will be always withdrawn.
     */
    withdraw?: boolean;
  }[];
}
