/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to stamp a file.
 */
export interface StampTangleRequest {
  /**
   * Alias tangle id. The new nft will belong to this alias.
   */
  aliasId?: string;
  /**
   * If specified, system will only use token amount for that exact period and refund the rest. Otherwise, it’ll use whatever it can.
   */
  days?: number;
  /**
   * Type of the tangle request.
   */
  requestType: 'STAMP';
  /**
   * Url for the file.
   */
  uri: string;
}
