/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to set swap as funded.
 */
export interface SwapSetFundedTangleRequest {
  /**
   * Type of the tangle request.
   */
  requestType: 'SET_SWAP_FUNDED';
  /**
   * Buildcore UID of the swap
   */
  uid: string;
}
