/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to create a swap order.
 */
export interface SwapCreateTangleRequest {
  /**
   * Requested base token amount
   */
  baseTokenAmount?: number;
  /**
   * Requested native token(s)
   */
  nativeTokens?: {
    amount: number;
    id: string;
  }[];
  /**
   * List of requested Buildcore NFT ids or NFT tangle ids
   */
  nfts?: string[];
  /**
   * Target member Buildcore uid or tangle address
   */
  recipient: string;
  /**
   * Type of the tangle request.
   */
  requestType: 'CREATE_SWAP';
  /**
   * If set to true swap order will be set to funded upon creation
   */
  setFunded?: boolean;
}
