/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Tangle request object to verify Ethereum address.
 */
export interface VerifyEthForB5TangleRequest {
  /**
   * Ethereum address.
   */
  ethAddress: string;
  /**
   * Type of the tangle request.
   */
  requestType: 'VERIFY_ETH_ADDRESS';
}
