name: Action | Deploy to WEN

on:
  push:
    branches:
      - develop

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set env vars
        working-directory: packages/functions
        run: echo "$FUNCTIONS_ENV_VARS" >> .env.preview
        env:
          FUNCTIONS_ENV_VARS: ${{ secrets.FUNCTIONS_ENV_VARS_TEST }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:indexes -P soonaverse-test -f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy_hosting:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: packages/ui
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soonaverse/ui
      - name: Build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE_TEST }}'
          projectId: 'soonaverse-test'
          channelId: live
          target: def-host
  roll-firestore:
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 360
    needs: [deploy_functions, deploy_hosting]
    defaults:
      run:
        working-directory: packages/functions
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npx lerna bootstrap --scope=@soonaverse/functions
          npm i -g ts-node
      - name: Create serviceAccountKey.json
        run: echo "$SERVICE_ACCOUNT" >> scripts/serviceAccountKey.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE_TEST }}
      - name: Roll firestore
        run: cd scripts && ts-node db.upgrade.ts
