name: Action | Deploy to WEN

on: pull_request

jobs:
  roll-firestore:
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 360
    defaults:
      run:
        working-directory: packages/functions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '10'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set env vars
        run: echo "$ENV_VARS" > .env
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
      - name: Create serviceAccountKey.json
        run: echo "$SERVICE_ACCOUNT" > scripts/serviceAccountKey.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Install dependencies
        run: |
          npm i -g ts-node
          cd ../../ && npm run build:functions
      - name: Roll firestore
        run: cd scripts && ts-node db.upgrade.ts
