name: Action | Deploy to Preview (PR)

on:
  pull_request:
    paths:
      - packages/ui/**

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: packages/ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies & build
        run: cd ../../ && npm run build:ui
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE_TEST }}'
          projectId: 'soonaverse-test'
          expires: 3d
          target: def-host
