name: Action | Deploy to Production

on: pull_request

jobs:
  roll-firestore:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 360
    defaults:
      run:
        working-directory: packages/functions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set env vars
        run: echo "$ENV_VARS" > .env
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
      - name: Install dependencies
        run: |
          npm i -g ts-node
          cd ../../ && npm run build:functions
      - name: Roll firestore
        run: cd scripts && ts-node db.upgrade.ts
