name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy_hosting:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: packages/ui
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soonaverse/ui
      - name: Build
        run: npm run build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE }}'
          projectId: 'soonaverse'
          channelId: live
          target: 5d1024cf-d55e-4b10-9d27-eccc37e80161
  deploy_functions:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:indexes -P soonaverse -f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}