name: Action | Deploy to Preview (PR)

on:
  pull_request:
    paths:
      - packages/ui/**

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: packages/ui
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soonaverse/ui
      - name: Build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE_TEST }}'
          projectId: 'soonaverse-test'
          expires: 3d
          target: def-host
