name: Client | lint

on:
  pull_request:
    paths:
      - packages/client/**
      - packages/api/**

jobs:
  soon_lib:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm run build:client
      - name: Prettier
        run: npm run prettier:client
      - name: Lint
        run: cd packages/client && npm run lint
