name: Firebase Functions - DEPLOY Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name:  Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions --force default
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
