name: Firebase Deploy DEV

on:
  push:
    branches:
      - develop
    paths:
      - packages/functions/**
      - packages/indexes/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soon/functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions,firestore:indexes -P soonaverse-dev -f
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
