name: Firebase function deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name:  Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions --force
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
