name: Deploy to PREVIEW

on:
  push:
    branches:
      - develop

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: stagging
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE_TEST }}"
          projectId: "soonaverse-test"
          channelId: live
          target: prod
