name: Firebase Deploy DEV

on:
  push:
    branches:
      - online_testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: emulator
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: echo okokok
