name: Firebase Functions - DEPLOY WEN

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions,firestore:indexes -P soonaverse-test -f
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
