name: Functions Emulated Unit Tests

on: push

jobs:
  functions_unit_tests_emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "export LOCAL_TEST=true && jest test/controls/award.spec.ts --ci" --project dev

  functions_unit_tests_emulator_test2:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "export LOCAL_TEST=true && jest test/controls/collection.spec.ts --ci" --project dev
