name: Functions | Online Emulated Unit Tests

on:
  workflow_run:
    workflows: ["Firebase Deploy DEV"]
    types: [completed]
    branches:
      - "develop"

jobs:
  npm-install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx lerna bootstrap --scope=@soonaverse/functions

  chunk_0:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/api/custom.get.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/api/getById.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/api/getMany.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/api/getTokenPrice.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/api/getUpdatedAfter.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_0
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_1:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/auth.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/address.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/award.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/collection.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/member.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_1
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_2:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/controls/nft-bidding.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/nft.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/order.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/proposal.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/space.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_2
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_3:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/controls/stake.reward.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token-distribution-auto-trigger.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token-distribution.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token-trade.buy.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token-trade.sell.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_3
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_4:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/controls/token-trade.trigger.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token.expired.sale.cron.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token.order.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/token.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/controls/workflow-online.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_4
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_5:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/controls/workflow.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/dbRoll/set.extra.stakes.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/dbRoll/space.vaultAddress.roll.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/stake/stake.reward.cron.spec.ts &&
                npm run test-online:ci -- --findRelatedTests ./test/storage/resize.img.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_5
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_6:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools@11.14.1
          npm install -g npm-run-all
      - name: Test
        working-directory: packages/functions
        run: npm run milestone-sync & firebase emulators:exec "
                npm run test-online:ci -- --findRelatedTests ./test/storage/storage.roll.spec.ts 
             " --project dev --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-online-chunk_6
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

