name: Functions Unit Tests

on: push

jobs:
  functions_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: firebase emulators:exec --only database,functions,firestore \"npm run test\"

