name: Functions | Lint

on:
  pull_request:
    paths:
      - packages/functions/**

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm run build:functions
      - name: Prettier
        run: npx prettier --check packages/functions
      - name: Lint
        run: cd packages/functions && npm run lint
