name: Functions | Emulated Unit Tests

on:
  pull_request:
    paths:
      - packages/functions/**

jobs:
  npm-install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx lerna bootstrap --scope=@soonaverse/functions

  chunk_0:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/keep-live.spec.ts &&
                npm run test:ci -- --findRelatedTests test/db.roll.spec.ts &&
                npm run test:ci -- --findRelatedTests test/auth.spec.ts &&
                npm run test:ci -- --findRelatedTests test/storage/resize.img.spec.ts &&
                npm run test:ci -- --findRelatedTests test/stake/stake.reward.cron.spec.ts &&
                npm run test:ci -- --findRelatedTests test/stake/delete.stake.reward.spec.ts &&
                npm run test:ci -- --findRelatedTests test/dbRoll/0.19/roll.member.avatars.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_0
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_1:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/dbRoll/0.19/avatar.collection.spec.ts &&
                npm run test:ci -- --findRelatedTests test/cron/proposal.cron.spec.ts &&
                npm run test:ci -- --findRelatedTests test/cron/nft-stake.cron.spec.ts &&
                npm run test:ci -- --findRelatedTests test/cron/floor-price.cron.only.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/workflow.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/workflow-online.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token.order.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_1
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_2:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/controls/token.expired.sale.cron.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token-trade.trigger.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token-trade.sell.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token-trade.buy.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token-distribution.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token-distribution-auto-trigger.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/stake.reward.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_2
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_3:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/controls/space.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/proposal.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/order.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/nft.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/nft-bidding.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/member.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/collection.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_3
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_4:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/controls/address.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.vote.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.update.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.set.to.sale.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.rank.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.order.and.claim.air.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.create.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_4
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_5:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/controls/token/token.cancel.pub.sale.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.airdrop.spec.ts &&
                npm run test:ci -- --findRelatedTests test/controls/token/token.airdrop.claim.spec.ts &&
                npm run test:ci -- --findRelatedTests test/api/getUpdatedAfter.spec.ts &&
                npm run test:ci -- --findRelatedTests test/api/getTokenPrice.spec.ts &&
                npm run test:ci -- --findRelatedTests test/api/getMany.spec.ts &&
                npm run test:ci -- --findRelatedTests test/api/getById.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_5
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

  chunk_6:
    needs: npm-install
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        with:
          path: |
           node_modules
           packages/functions/node_modules
           packages/interfaces/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Init
        run: |
          npm run build:functions
          npm install -g firebase-tools
      - name: Test
        working-directory: packages/functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./test-service-account-key.json"
          npm run milestone-sync &
          firebase emulators:exec "
                npm run test:ci -- --findRelatedTests test/api/getAddresses.spec.ts &&
                npm run test:ci -- --findRelatedTests test/api/custom.get.spec.ts 
             " --project dev --only functions,firestore,storage,ui,auth --export-on-exit=./firestore-data
      - name: Archive firestore data
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
           name: firestore-data-test-chunk_6
           path: ./packages/functions/firestore-data/
           retention-days: 1
      - name: Analyze Test and Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: packages/functions/reports/test
          coverage_format: COBERTURA/XML
          coverage_path: packages/functions/reports/coverage

