name: Functions Unit Tests

on: push

jobs:
  functions_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: firebase emulators:exec --only database,functions,firestore "npm run test"

