name: Functions Emulated Unit Tests
on: push
jobs:

  functions_unit_tests_emulator_award-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/award.spec.ts" --project dev

  functions_unit_tests_emulator_collection-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/collection.spec.ts" --project dev

  functions_unit_tests_emulator_member-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/member.spec.ts" --project dev

  functions_unit_tests_emulator_nft-bidding-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/nft-bidding.spec.ts" --project dev

  functions_unit_tests_emulator_nft-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/nft.spec.ts" --project dev

  functions_unit_tests_emulator_order-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/order.spec.ts" --project dev

  functions_unit_tests_emulator_proposal-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/proposal.spec.ts" --project dev

  functions_unit_tests_emulator_space-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/space.spec.ts" --project dev

  functions_unit_tests_emulator_token-distribution-auto-trigger-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token-distribution-auto-trigger.spec.ts" --project dev

  functions_unit_tests_emulator_token-distribution-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token-distribution.spec.ts" --project dev

  functions_unit_tests_emulator_token-trade-buy-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token-trade.buy.spec.ts" --project dev

  functions_unit_tests_emulator_token-trade-sell-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token-trade.sell.spec.ts" --project dev

  functions_unit_tests_emulator_token-trade-trigger-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token-trade.trigger.spec.ts" --project dev

  functions_unit_tests_emulator_token-expired-sale-cron-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token.expired.sale.cron.spec.ts" --project dev

  functions_unit_tests_emulator_token-order-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token.order.spec.ts" --project dev

  functions_unit_tests_emulator_token-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test -- --findRelatedTests ./test/controls/token.spec.ts" --project dev

