name: Functions Unit Tests

on: push

jobs:
  front_end_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: npm install
      - name: Run tests
        run: |
          npm run emulate &
          sleep 60 &&
          npm run test

