name: Functions Unit Tests

on: push

jobs:
  front_end_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: npm install
      - run: npm run emulate &
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - run: npm run test

