name: SDK | test-examples

on:
  pull_request:
    paths:
      - packages/sdk/**
      - packages/search/**

jobs:
  test-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies and build SDK
        run: npm run build:sdk
      - name: Install and build Examples
        run: npm i && npm run build
        working-directory: packages/sdk/examples
