name: SDK | lint

on:
  pull_request:
    paths:
      - packages/sdk/**
      - packages/search/**

jobs:
  prettier_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm run build:sdk
      - name: Prettier
        run: cd packages/sdk && npx prettier --check .
      - name: Lint
        run: cd packages/sdk && npm run lint
