name: Soon lib lint & test

on:
  pull_request:
    paths:
      - packages/lib/**

jobs:
  soon_lib:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/lib
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soonaverse/lib
      - name: Prettier
        run: npx prettier --check .
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
