name: Tangle - Functions Emulated Unit Tests

on:
  pull_request:
    paths:
      - functions/**

jobs:
  npm-intstall:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  job_0:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/address.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_1.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_10.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_2.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_3.spec.ts\" 
             "
  job_1:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_4.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_5.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_6.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_7.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_8.spec.ts\" 
             "
  job_2:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_9.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_1.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_10.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_11.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_12.spec.ts\" 
             "
  job_3:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_2.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_3.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_4.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_5.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_6.spec.ts\" 
             "
  job_4:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_7.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_8.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_9.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-nft-trading/minted-nft-trading_1.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-nft-trading/minted-nft-trading_2.spec.ts\" 
             "
  job_5:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-nft-trading/minted-nft-trading_3.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-airdrop/minted-token-airdrop_1.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-airdrop/minted-token-airdrop_2.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-airdrop/minted-token-airdrop_3.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_1.spec.ts\" 
             "
  job_6:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_10.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_11.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_12.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_13.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_14.spec.ts\" 
             "
  job_7:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_16.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_2.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_3.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_4.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_5.spec.ts\" 
             "
  job_8:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_6.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_7.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_8.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_9.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/staking/staking_1.spec.ts\" 
             "
  job_9:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/token.claim.minted.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/token.mint.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/trade-base-token-order.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/tran.match.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/transaction-trigger.spec.ts\" 
             "
  job_10:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/withdraw-deposit-nft/deposit-withraw-nft_1.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/withdraw-deposit-nft/deposit-withraw-nft_2.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/withdraw-deposit-nft/deposit-withraw-nft_3.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/withdraw-deposit-nft/deposit-withraw-nft_4.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/withdraw-deposit-nft/deposit-withraw-nft_5.spec.ts\" 
             "
  job_11:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/workflow-online.spec.ts\" 
             \"test-tangle -- --findRelatedTests ./test-tangle/workflow.spec.ts\" 
             "
  job_12:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/base-token-trading/base-token-trading_11.alone.spec.ts\" 
             "
  job_13:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools@11.14.1
      - run: npm install -g npm-run-all
      - run: npm run build
      - run: firebase use dev
      - run: firebase emulators:exec 
             "run-p 
             \"test-tangle -- --findRelatedTests ./test-tangle/minted-token-trade/minted-token-trade_15.alone.spec.ts\" 
             "
