name: Tangle - Functions Emulated Unit Tests
on: push
jobs:

  address-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/address.spec.ts" --project dev

  base-token-trading-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/base-token-trading.spec.ts" --project dev

  collection-minting/collection-minting_1-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_1.spec.ts" --project dev

  collection-minting/collection-minting_2-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_2.spec.ts" --project dev

  collection-minting/collection-minting_3-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_3.spec.ts" --project dev

  collection-minting/collection-minting_4-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_4.spec.ts" --project dev

  collection-minting/collection-minting_5-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_5.spec.ts" --project dev

  collection-minting/collection-minting_6-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_6.spec.ts" --project dev

  collection-minting/collection-minting_7-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_7.spec.ts" --project dev

  collection-minting/collection-minting_8-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_8.spec.ts" --project dev

  collection-minting/collection-minting_9-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/collection-minting/collection-minting_9.spec.ts" --project dev

  deposit-withraw-nft-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/deposit-withraw-nft.spec.ts" --project dev

  minted-token-trading-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/minted-token-trading.spec.ts" --project dev

  token-claim-minted-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/token.claim.minted.spec.ts" --project dev

  token-mint-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/token.mint.spec.ts" --project dev

  trade-base-token-order-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/trade-base-token-order.spec.ts" --project dev

  tran-match-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/tran.match.spec.ts" --project dev

  transaction-trigger-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/transaction-trigger.spec.ts" --project dev

  workflow-spec-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase emulators:exec --only functions,firestore "npm run test-tangle -- --findRelatedTests ./test-tangle/workflow.spec.ts" --project dev

